name = "BigO"
uuid = "2ecab122-4940-479f-a518-03695d136e3f"
authors = ["Endre Márk Borza"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
